### PR TITLE
added junit and regression tests for user stories

### PR DESCRIPTION
**Pull request by jeffgan96**

### CODE REVIEW

**Review by jothipillay — CHANGES_REQUESTED** [review]
Hey Jeff,

In the AddUserStoryToCommandSystemTest.java, I believe there are some errors in the javadoc comments for your assertSuccess methods used in your system tests.

**Review by jothipillay — COMMENTED** [review]
In addition, 

Currently, I believe that a user story with the same user, function and reason but with different importance is not considered as a duplicate when added to a project. I think you should consider this as duplicates as it is unlikely that there is going to be 2 user stories with the exact same user, function and reason but with a different importance. Any upgrading or downgrading of the importance can be handled by the edit method. Maybe you can reconsider

**Comment by jeffgan96** [comment]
Hi @jothipillay 

Thanks for your comments. A user story with only the same importance, user, function and reason can be regarded as the same object. ie story1.equals(story2) returns true
However, as pointed out by you there might actually be benefits in simply comparing the user, function and reason to prevent users from keying in the same details but indicating a different importance. For such cases, the isSameUserStory() is used instead to compare the fields. both are included as part of the user story class.

**Comment by jothipillay** [comment]
@jeffgan96 
Thank you for your prompt reply and clarifying.

**Review by jothipillay — APPROVED** [review]

**Pull request merged**
